<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name = "viewport" content = "with=device-width,initial-scale = 1.0">
    <title>University Website design</title>
    <link rel="stylesheet" href="styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
  </head>
  <body>
    <section class = "header">
      <nav>
        <a href="logo.jpeg"><img src="logo.jpeg" alt=""></a>
        <div class="nav-links" id = "navLinks">
          <i class="fas fa-window-close" onclick="hideMenu()"></i>
          <ul>
            <li><a href="index.php">HOME</a></li>
            <li><a href="about.php">ABOUT</a></li>
            <li><a href="https://www.cuchd.in/international/undergraduate/#undergraduate" target="_blank">COURSE</a></li>
            <li><a href="contact.php">CONTACT</a></li>
            <li><a href="login.php">LOG IN</a></li>
          </ul>

        </div>
        <i class="fas fa-bars" onclick="showMenu()"></i>

      </nav>
      <section>
        <div class="Details">
            <h2 class="head1"style="margin-top:20px">About Student Management System</h2>
            <p class="SMS About" style="margin-top:15px">Schools and Universities are the foundation of knowledge and an educational body on which students rely upon. Therefore, they need to maintain a proper database of its students to keep all the updated records and easily share information
                with students.
                <P class="SMS About">Most schools and Universities count on an advanced software tool knows as 'Student Information System (SIS)' to keep all their student records and administrative operations including, examinations, attendance, and other activities.
                </P>
                <P class="SMS About">Over the recent years, the performance and efficiency of the education industry have been enhanced by using the Student Management System. This tool has productively taken over the workload of the admin department with its well-organized,
                    easy, and reliable online school management software.</P>
            </p>
            <p class="SMS About"style="margin-top:-20px">"Student Management System (SMS) is a solution tool that is designed to track, maintain and manage all the data generated by a School, including the grades of a student, their attendance, their interpersonal activities records, etc.,"
                SMS acts as the bottom line database to store all the day-to-day school operations, maintain the proper records of the past few decades, regulate the various operation modules, managing the critical tasks, efficiently handling the
                administrative processes</p>
        </div>
      </section>
      <section>
        <div class="row">
            <div class="column Details">
                <h2 class="head">VISSION</h2>
                <p class="About">"Empower the educational services in ever changing environment to create better opportunities for the students and teachers for their consistent growth."
                </p>
            </div>
      
            <div class="column Details">
                <h2 class="head">MISSION</h2>
                <p class="About">"We Strive to build strong communication network with more institution focused educational services so that we can endeavor 100% customer satisfaction."
      
      
                </p>
            </div>
      
            <div class="column Details">
                <h2 class="head">VALUES</h2>
      
                <p class="About">The most important Core value that we have integrated into our system is Client's Satisfaction, Dedication, Innovation and hardwork </p>
            </div>
        </div>
        <div id="mySidenav" class="sidenav">
        </div>
    </section>
</section> 
</div>
  </body>
</html>
